import 'package:cinco_cartas/classes/cartas.dart';
import 'package:flutter/material.dart';

List<CartasClass> cartasNaoUsada = [
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
];

List<CartasClass> cartasUsada = [
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('B', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('10', Colors.red.shade300, Icons.heart_broken_rounded),
];
List<CartasClass> cartasUser = [
  CartasClass('A', Colors.black54, Icons.api_rounded),
  CartasClass('A', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('A', Colors.black54, Icons.spa_rounded),
  CartasClass('X', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('10', Colors.red.shade300, Icons.heart_broken_rounded),
  CartasClass('10', Colors.black54, Icons.api_rounded),
];
